Repository matrix-org/matrix-rust-sdk, pull requests merged in 2022-09, with the labels that each got.

#988 feat(crypto): Rename `verified` and `deleted` to `is_*`
  bindings/matrix-sdk-crypto-ffi/src/machine.rs
  bindings/matrix-sdk-ffi/src/session_verification.rs
  crates/matrix-sdk-crypto/src/backups/mod.rs
  crates/matrix-sdk-crypto/src/gossiping/machine.rs
  crates/matrix-sdk-crypto/src/identities/device.rs
  crates/matrix-sdk-crypto/src/identities/user.rs
  crates/matrix-sdk-crypto/src/machine.rs
  crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
  crates/matrix-sdk/src/docs/encryption.md
  crates/matrix-sdk/src/encryption/identities/devices.rs
  crates/matrix-sdk/src/encryption/identities/users.rs
  crates/matrix-sdk/src/encryption/mod.rs
  crates/matrix-sdk/src/room/common.rs
  examples/emoji_verification/src/main.rs
Labels: enhancement

#1018 feat(qrcode): Allow `VerificationData` to receive a flow ID
  crates/matrix-sdk-crypto/src/types/events/olm_v1.rs
  crates/matrix-sdk-crypto/src/verification/mod.rs
  crates/matrix-sdk-crypto/src/verification/qrcode.rs
  crates/matrix-sdk-qrcode/src/error.rs
  crates/matrix-sdk-qrcode/src/lib.rs
  crates/matrix-sdk-qrcode/src/types.rs
Labels: enhancement

#1024 feat(qrcode): Remove decoding QR code from an image
  Cargo.lock
  crates/matrix-sdk-qrcode/Cargo.toml
  crates/matrix-sdk-qrcode/README.md
  crates/matrix-sdk-qrcode/data/self-no-master.png
  crates/matrix-sdk-qrcode/data/self-verification.png
  crates/matrix-sdk-qrcode/data/verification.png
  crates/matrix-sdk-qrcode/src/error.rs
  crates/matrix-sdk-qrcode/src/lib.rs
  crates/matrix-sdk-qrcode/src/types.rs
  crates/matrix-sdk-qrcode/src/utils.rs
Labels: enhancement

#788 feat(crypto-js): Implement key verification
  Cargo.lock
  bindings/matrix-sdk-crypto-js/Cargo.toml
  bindings/matrix-sdk-crypto-js/package.json
  bindings/matrix-sdk-crypto-js/src/device.rs
  bindings/matrix-sdk-crypto-js/src/identifiers.rs
  bindings/matrix-sdk-crypto-js/src/lib.rs
  bindings/matrix-sdk-crypto-js/src/machine.rs
  bindings/matrix-sdk-crypto-js/src/requests.rs
  bindings/matrix-sdk-crypto-js/src/store.rs
  bindings/matrix-sdk-crypto-js/src/types.rs
  bindings/matrix-sdk-crypto-js/src/verification.rs
  bindings/matrix-sdk-crypto-js/src/vodozemac.rs
  bindings/matrix-sdk-crypto-js/tests/device.test.js
  bindings/matrix-sdk-crypto-js/tests/helper.js
  bindings/matrix-sdk-crypto-js/tests/machine.test.js
  crates/matrix-sdk-crypto/src/verification/mod.rs
Labels: enhancement, bindings

#1043 fix(jack-in): limit log4rs features to minimum
  Cargo.lock
  labs/jack-in/Cargo.toml
  labs/jack-in/src/main.rs
Labels: Security

#1039 feat(crypto-js): Implement `OlmMachine.get_identity`
  bindings/matrix-sdk-crypto-js/src/device.rs
  bindings/matrix-sdk-crypto-js/src/identifiers.rs
  bindings/matrix-sdk-crypto-js/src/identities.rs
  bindings/matrix-sdk-crypto-js/src/js.rs
  bindings/matrix-sdk-crypto-js/src/lib.rs
  bindings/matrix-sdk-crypto-js/src/machine.rs
  bindings/matrix-sdk-crypto-js/src/macros.rs
  bindings/matrix-sdk-crypto-js/src/olm.rs
  bindings/matrix-sdk-crypto-js/src/store.rs
  bindings/matrix-sdk-crypto-js/src/sync_events.rs
  bindings/matrix-sdk-crypto-js/src/types.rs
  bindings/matrix-sdk-crypto-js/src/verification.rs
  bindings/matrix-sdk-crypto-js/src/vodozemac.rs
  bindings/matrix-sdk-crypto-js/tests/identifiers.test.js
  bindings/matrix-sdk-crypto-js/tests/machine.test.js
  crates/matrix-sdk-crypto/src/identities/user.rs
Labels: enhancement, bindings

#1059 feat(crypto-js): Implement `OlmMachine.export_room_keys` and `.import_room_keys`
  bindings/matrix-sdk-crypto-js/src/machine.rs
  bindings/matrix-sdk-crypto-js/src/olm.rs
  bindings/matrix-sdk-crypto-js/tests/device.test.js
  bindings/matrix-sdk-crypto-js/tests/machine.test.js
Labels: enhancement, bindings
